### ISSUE TITLE
TSC Charter Creation

### ISSUE THREAD

**Issue by louisa-seers** [galasa-dev/TSC#17]
# Story
As a potential contributor to the Galasa project, I want to know the rules of engagement with the project are fair, just and transparent, so I can properly decide whether to participate or not.

# Background
Here is the Zowe Charter creation - https://github.com/zowe/community/blob/master/Technical-Steering-Committee/charter.md

[galasa-tsc-charter.md](https://github.com/galasa-dev/TSC/files/14269521/galasa-tsc-charter.md)

Attached is the Zowe charter for us to amend and put a skeleton charter in place.

A Galasa charter needs to be small, as we can always change it later.

It should include:
- behaviour rules
- how you get to be a contributor
- how you get a vote on the TSC

We need to decide where to publish it:
For example:
- In the galasa-dev docs ?
- On the TSC github pages site ?

# Tasks
- [ ] Review the zowe and other project charters for inspiration
- [ ] Draft the Galasa charter
- [ ] Review the charter with interested parties for comment
- [ ] Ratify the charter at a TSC meeting
- [ ] Publish the charter somewhere (TBD)
- [ ] Link from every readme in the code to these documents so people are signposted there easily.

**Comment by louisa-seers** [comment]
[galasa-tsc-charter.md](https://github.com/galasa-dev/TSC/files/14434892/galasa-tsc-charter.md)

@hobbit1983 - I have made a few adjustments but interested to see your point of view. Once you have reviewed, I'll look to seek feedback from the wider TSC.

**Comment by louisa-seers** [comment]
My intention is to publish the charter on www.github.com/galasa-dev/TSC.

**Comment by jadecarino** [comment]
My initial thoughts on the TSC Charter draft:
Overall, I think it's really comprehensive, and covers all of our needs at the point the project currently is. 
There were a few points that I feel need clarifying or expanding, however I might have just misunderstood so would be good to discuss in the TSC meeting tomorrow.
1) 2.3.1 and 2.3.2 - I don't think the distinction between a Contributor and a Committer is very clear here as from my understanding, you would need committer rights on the source code to be able to contribute code or documentation, which is what a Contributor can do. In terms of the 'other technical artifacts', if this includes things that you don't need committer rights for, can we give some examples of what this might be? Is it raising stories, giving suggestions ideas, providing access to software? I'd just like some clarification here.
2) 2.3.3 - Can we explain what sort of behaviours might cause the Committers to move to remove someone as a Committer?
3) 4.5 - Do we want to ensure this is met before releasing this charter? We still have Slack channels that are on the IBM-internal workspace, for users and development. Alternatively, should we specify that there may be some channels kept internal for certain reasons?

**Comment by hobbit1983** [comment]
@jadecarino some good comments here - thank you.

The difference between a contributor and a committer is that a contributor can branch the code, push that branch to the repository and create a PR but cannot merge that PR into main.  Only a committer has that authority.

I think we could perhaps suggest reason, but we cannot supply an exhaustive list of actions that might get some-one revoked.

We should remove those channels, however they are still open and transparent, All of the Galasa meetings should be held in this way with no meetings behind closed doors.

**Comment by louisa-seers** [comment]
Louisa actions from the TSC meeting on the 12th March.

- [ ] Define a contributor.
- [ ] Define a committer.
- [ ] Define TSC voting member.
- [ ] Create a file in the TSC repository that contains the contributor GitHub IDs.
- [ ] Create a file in the TSC repository that contains the committer GitHub IDs.
- [ ] Create a list of items that the TSC is responsible for and would vote on. For example: quarterly roadmap votes, cadence of releases, etc.

Items for the next TSC:

- [ ] Decide what is a votable topic and how we vote.
- [ ] Decide the minimum number for a quorum.
- [ ] Decide on whether we are happy with who is in which category.

**Comment by louisa-seers** [comment]
After speaking to John Mertic, he has informed me that the charter I have used is actually part of the base charter that all projects sign up to when they have joined the OMP: https://github.com/openmainframeproject/foundation/blob/main/project_charters/galasa_charter.pdf

Therefore, what I should create is in fact a governance file, so I will add that as a new issue to track with the same information.
